using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Player : MonoBehaviour
{

    public float gravity;
    public Vector2 velocity;
    public float MaxAcceleration = 10;
    public float acceleration = 10;
    public float distance = 0;
    public float jumpVelocity = 20;
    public float MaxXVelocity = 100;
    public float groundHeight = 10;
    public bool isGrounded = false;
    public bool isHoldingJump = false;
    public float maxHoldJumpTime = 0.4f;
    public float holdJumpTimer = 0.0f;
    public float jumpGroundThreshold = 1;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        Vector2 pos = transform.position;

       float groundDistance =  Mathf.Abs(pos.y - groundHeight);
        if (isGrounded || groundDistance <= jumpGroundThreshold)
        {
            if(Input.GetKeyDown(KeyCode.Space))
            {
                isGrounded = false;
                velocity.y = jumpVelocity;
                isHoldingJump = true;
                holdJumpTimer = 0;
            }
            if (Input.GetKeyUp(KeyCode.Space))
            {
                isHoldingJump = false;
            }
        }
    }

    private void FixedUpdate()
    {
        Vector2 pos = transform.position;

        if (!isGrounded)
        {
            if (isHoldingJump)
            {
                holdJumpTimer = +Time.fixedDeltaTime;
                if(holdJumpTimer >= maxHoldJumpTime)
                {
                    isHoldingJump = false; 
                }
            }

            pos.y += velocity.y * Time.fixedDeltaTime;
            if (!isHoldingJump)
            {
                velocity.y += gravity * Time.fixedDeltaTime;
            }
            

            if(pos.y <= groundHeight)
            {
                pos.y = groundHeight;
                isGrounded = true;

            }
            distance += velocity.x * Time.fixedDeltaTime;
            if (isGrounded)
            {
                float velocityRatio = velocity.x / MaxXVelocity;
                acceleration = MaxAcceleration * (1 - velocityRatio);

                velocity.x += acceleration * Time.fixedDeltaTime;
               
                if(velocity.x >= MaxXVelocity)
                {
                    velocity.x = MaxXVelocity;
                }
            }

        }
        transform.position = pos;
    }
}
